In [1]:
import numpy as np
import torch as tch

In [2]:
dtype = tch.FloatTensor

In [3]:
a = np.zeros((500,3))
np.shape(a)
a[:,1] = 1
a[:,2] = 2

In [4]:
a

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       ...,
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [5]:
b = np.eye(500)

In [6]:
tch_a = tch.from_numpy(a)
tch_b = tch.from_numpy(a.T)

In [7]:
tch_a

tensor([[ 0.,  1.,  2.],
        [ 0.,  1.,  2.],
        [ 0.,  1.,  2.],
        ...,
        [ 0.,  1.,  2.],
        [ 0.,  1.,  2.],
        [ 0.,  1.,  2.]], dtype=torch.float64)

In [8]:
tch_b

tensor([[ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  ...,  2.,  2.,  2.]], dtype=torch.float64)