# Simple toy example for HMRF-GMM

Circle example

Reflects `toy_example.m`

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
%matplotlib inline

In [3]:
block_size = 40

In [14]:
x = np.arange(0,block_size)
y = np.arange(0,block_size)
z = np.array([0])
order = 1

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
grid_matrix = np.meshgrid(np.arange(len(x)), 
                          np.arange(len(y)), 
                          np.arange(len(z)))

In [69]:
np.meshgrid(np.arange(1,4), np.arange(1,4), np.ones(3)) #, np.arange(1,1))

[array([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],
 
        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],
 
        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]]), array([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],
 
        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]]), array([[[ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.]],
 
        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.]],
 
        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]])]

In [61]:
np.arange(1,4)

array([1, 2, 3])

In [19]:
grid_matrix.shape
num_of_elements = grid_matrix.shape[0]

In [5]:
# construct element - reflects constructElements.m
def constructElement(x,y,z,order):
    grid

In [40]:
class Element(object):
    """Class definition (instead of Matlab stuct)"""
    
    def __init__(self, grid_matrix, x, y, z):
        self.Grid = grid_matrix
        self.Center = [x[grid_matrix[:,0]],
                       y[grid_matrix[:,1]],
                       z[grid_matrix[:,2]]]
        
        self.num_of_elements = grid_matrix.shape[0]
        
        self.Degree = np.empty(self.num_of_elements)
        self.Color = np.empty(self.num_of_elements)
        # fill with nan values
        self.Degree.fill(np.nan)
        self.Color.fill(np.nan)
        
    def find_neighbours(self):
        pass
        

In [43]:
E = Element(grid_matrix, x, y, np.zeros_like(x))

In [46]:
E.Center

[array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]]), array([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]

In [49]:
grid_matrix[:,0]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])